Feature/loggin
WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-1-Team-D pull request #13
Opened 2024-10-31 14:57 UTC by NicolasSokolowski

2024-10-31 15:23 UTC, pjroggy submitted a review, later dismissed

2024-10-31 15:39 UTC, Ektoplasme approved these changes, later dismissed

2024-10-31 15:39 UTC, pjroggy approved these changes, later dismissed

2024-10-31 15:55 UTC, jujuck requested changes

2024-10-31 15:55 UTC, jujuck commented on client/src/views/ConnexionPage/ConnexionPage.tsx
> +    <div className="bg-co-ctn">
Une balise main, at least

2024-10-31 15:55 UTC, jujuck commented on client/src/views/ConnexionPage/ConnexionPage.tsx
> +    <div className="bg-co-ctn">
Et une header

2024-10-31 15:55 UTC, jujuck commented on client/src/views/Home/Home.tsx
>        <Button
Mettre un link

2024-10-31 15:55 UTC, jujuck commented on client/src/context/AuthContext.tsx
> +  const [loginMutation, { loading, error }] = useMutation(LOGIN);
Cela doit etre un useLoginMutation()

2024-10-31 15:55 UTC, jujuck commented on client/src/context/AuthContext.tsx
> +import { LOGIN } from "../schemas/login";
Pas besoin

2024-11-01 17:14 UTC, pjroggy approved these changes

2024-11-02 09:25 UTC, Ektoplasme approved these changes

2024-11-04 07:55 UTC, Pas-nou approved these changes

2024-11-05 07:57 UTC, jujuck approved these changes

2024-11-05 07:58 UTC, merged