Feature/swipe page
WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-1-Team-D pull request #19
Opened 2024-11-06 17:12 UTC by Ektoplasme

### Adds Swipe Page

Creation of the Swipe component:

- I used [react-spring](https://react-spring.dev/) + [use-gesture](https://use-gesture.netlify.app/) to make the cards animations and drag events
- Added a query to get all the cats profile to swipe: only those we didn't like or dislike
- "Pagination" system, triggers 5 new cards redistribution when the stack is empty
- Added 2 mutations for like and dislike
- Added a modal popup that is triggered when a like mutation returns isMatch=true
- Updated overall style, layout, mobile format, added gifs...

![azdazdazd-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/4b8b2d14-9f10-4cc1-817e-5bfa32694140)

(Video is a gif, so it's normal that it's low fps)

2024-11-06 17:24 UTC, NicolasSokolowski submitted a review, later dismissed
👍 👍 👍

2024-11-06 17:36 UTC, Pas-nou submitted a review, later dismissed
2 petites choses à modifier, mais là t'as abbattu du gros travail 😸

2024-11-06 17:36 UTC, Pas-nou commented on client/src/components/SwipeCard/SwipeCard.tsx
> +        <img src={profile_picture} loading="lazy" alt="" />
ton `alt=""` est vide ici

2024-11-06 17:36 UTC, Pas-nou commented on client/src/main.tsx
> +// import { Home } from "./views/Home/Home";
👀

2024-11-06 22:47 UTC, pjroggy approved these changes, later dismissed

2024-11-07 08:49 UTC, Pas-nou approved these changes, later dismissed

2024-11-07 08:54 UTC, NicolasSokolowski submitted a review, later dismissed

2024-11-07 08:57 UTC, pjroggy submitted a review, later dismissed

2024-11-07 10:31 UTC, jujuck requested changes

2024-11-07 10:31 UTC, jujuck commented on client/src/components/SwipeCard/SwipeCard.tsx
> +              <li key={index}>
Attention, pas d'index en key. Cela contourne les règles d'optimisation de rendu de react

2024-11-07 10:31 UTC, jujuck commented on server/src/cats/cat.resolvers.ts
> +
Il manque une étape de réciprocité 
Si reciprocalLike, alors reciprocallike.isMatch = true puis save

2024-11-07 10:31 UTC, jujuck commented on server/src/cats/cat.resolvers.ts
> +      isMatch: reciprocalLike ? true : null, // Si like reciproque match true, si pas réciproque le laisser à null
ajout de la propriété: isLike : true

2024-11-07 10:31 UTC, jujuck commented on server/src/cats/cat.resolvers.ts
> +      isMatch: false,
isLike: false

2024-11-07 14:40 UTC, Pas-nou submitted a review, later dismissed

2024-11-07 14:47 UTC, pjroggy submitted a review, later dismissed

2024-11-07 16:27 UTC, Acetoshi reviewed
gg

2024-11-07 16:33 UTC, Pas-nou approved these changes
Purrfect

2024-11-07 16:33 UTC, Pas-nou commented on client/src/views/Likes/Likes.tsx
> +  const catId = 25;
L'utilisation du contexte sera utilisé sur la PR d'après

2024-11-07 16:34 UTC, pjroggy approved these changes

2024-11-08 08:03 UTC, jujuck approved these changes

2024-11-08 08:03 UTC, merged