Experimental/mise en place environment
WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-1-Team-D pull request #2
Opened 2024-10-16 15:45 UTC by Ektoplasme

### Mise en place d'une config de base avec un dossier client et un dossier server

**Il reste à faire:**
- La config Eslint et Prettier
- L'ajout de la bibliothèque [JoyUI](https://mui.com/joy-ui/getting-started/)
- L'ajout d'un script Husky
- D'autres suggestions?

🐱

2024-10-17 07:10 UTC, Pas-nou reviewed
Good job

2024-10-17 07:30 UTC, NicolasSokolowski commented
À ajouter dans le package.json côté server :

- class-validator
- @nic-jennings/sql-datasource
- type-graphql
- graphql-scalars
- dotenv

Ainsi qu'ajouter un script pour ts-node.

2024-10-17 07:44 UTC, NicolasSokolowski commented on client/package.json
> +  }
Joy UI à ajouter ?

2024-10-17 07:46 UTC, NicolasSokolowski commented on server/package.json
> +  }
À ajouter :

- class-validator
- type-graphql
- graphql-scalars
- dotenv

2024-10-17 07:58 UTC, NicolasSokolowski commented on server/src/index.ts
> +})()
Mise en place de dossiers : 

- resolvers
- entities
- helpers
- middlewares

<img width="208" alt="Screenshot 2024-10-17 at 09 57 17" src="https://github.com/user-attachments/assets/32245c3b-f399-4600-b0b7-13f3680da545">

2024-10-17 08:04 UTC, NicolasSokolowski requested changes
Bonne base pour débuter, 
architecture des dossiers à pawfiner et ajout de dépendances pour que l'équipe puisse commencer à coder :)

2024-10-17 08:10 UTC, pjroggy approved these changes, later dismissed
Vu avec les changements demandés par Nico

2024-10-18 06:50 UTC, pjroggy commented on client/src/App.css
> +.logo {
Ajouter @media (prefers-reduced-motion: no-preference) pour respecter le choix des utilisateurs qui ne veulent pas l'animation (pour mémoire)

2024-10-18 07:27 UTC, Pas-nou submitted a review, later dismissed
Purrfect 👍

2024-10-18 07:34 UTC, pjroggy approved these changes, later dismissed

2024-10-18 07:43 UTC, NicolasSokolowski approved these changes, later dismissed

2024-10-18 07:44 UTC, Pas-nou approved these changes, later dismissed
Good 🔩

2024-10-23 07:21 UTC, NicolasSokolowski submitted a review, later dismissed

2024-10-23 07:21 UTC, pjroggy submitted a review, later dismissed

2024-10-23 07:22 UTC, Pas-nou submitted a review, later dismissed
Good job ;)

2024-10-23 07:28 UTC, jujuck requested changes

2024-10-23 07:28 UTC, jujuck commented on client/src/main.tsx
> +  uri: "http://localhost:4000",
Mettre le client dans un fichier spécifique et passer l'uri en variable d'environnement

2024-10-23 07:28 UTC, jujuck commented on client/src/main.tsx
> +            <Routes>
Mettre en place de router dans sa nouvelle version en createBrowserRouter.. en mode objet

2024-10-23 07:28 UTC, jujuck commented on server/src/index.ts
> +  const server = new ApolloServer({ typeDefs, resolvers });
Mets en place un buildSchema avec un resolvers sur une entité qui comprends une méthode qui retourne "Hello"

2024-10-23 07:28 UTC, jujuck commented on client/package.json
> +    "@mui/joy": "^5.0.0-beta.48",
OK, parce que projet fictif. A ne pas faire sur un projet réel... Mode béta ??? pas stable

2024-10-23 08:41 UTC, Ektoplasme commented on client/src/theme.ts
J'avais oublié de le commit 💁‍♀️

2024-10-23 08:45 UTC, Pas-nou submitted a review, later dismissed
Ok

2024-10-23 08:47 UTC, pjroggy submitted a review, later dismissed

2024-10-23 10:04 UTC, Pas-nou commented on client/src/main.tsx
> +    errorElement: <Error />,
On peut avoir une erreur sur une page 404?

2024-10-23 10:05 UTC, Pas-nou approved these changes
Good 👍

2024-10-23 10:07 UTC, pjroggy approved these changes

2024-10-23 10:36 UTC, jujuck approved these changes

2024-10-23 10:36 UTC, jujuck commented on client/src/theme.ts
> +          // secondary: string;
Pas de commentaires inutiles

2024-10-23 10:36 UTC, jujuck commented on client/src/main.tsx
> +    element: <NoPage />,
Ajoute ErrorElement vers la même page

2024-10-23 10:36 UTC, jujuck commented on client/src/main.tsx
> +    errorElement: <Error />,
Normalement, non. ta page ne dois pas pouvoir générer d'erreur. La plupart des erreurs venant des requetes

2024-10-23 10:36 UTC, merged