Feature/account creation
WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-1-Team-D pull request #24
Opened 2024-11-07 22:44 UTC by NicolasSokolowski

Mise en place de la page de création de compte avec 1 premier formulaire listant les champs obligatoires, et un second pour les champs facultatifs.

![cat-creation](https://github.com/user-attachments/assets/1f71550d-fe47-4aa3-94e2-cea926ecb292)
(Le gif a ralenti le screen recording)

2024-11-07 23:14 UTC, pjroggy submitted a review, later dismissed

2024-11-08 08:16 UTC, Pas-nou reviewed
Sur l'input Name, je remplacerais le placeholder par "Nom" :)

2024-11-08 08:33 UTC, pjroggy approved these changes, later dismissed

2024-11-08 08:33 UTC, NicolasSokolowski commented
> Sur l'input Name, je remplacerais le placeholder par "Nom" :)

Merci c'est corrigé !

2024-11-08 08:35 UTC, Pas-nou approved these changes, later dismissed

2024-11-08 09:25 UTC, jujuck requested changes

2024-11-08 09:25 UTC, jujuck commented on client/src/components/TimePicker/TimePicker.tsx
> +    let adjustedHours = hours;
Pas besoin, déclare directement let [hours, minutes]

2024-11-08 09:25 UTC, jujuck commented on client/src/components/TimePicker/TimePicker.tsx
> +
PAs besoin de String dans une conaténation

2024-11-08 09:25 UTC, jujuck commented on client/src/components/TimePicker/TimePicker.tsx
> +    const [hours, minutes] = hoursMinutes.split(":").map(Number);
Passe en let et met un if else de réaffectation

2024-11-08 09:25 UTC, jujuck commented on server/src/cats/cat.resolvers.ts
> +      where: { email: emailLowerCase },
en direct email.toLowerCase (essaie)

2024-11-08 09:25 UTC, jujuck commented on server/src/cats/cat.resolvers.ts
> +    try {
Si tu dois déclarer la variable to lower case, le faire ici

2024-11-08 09:25 UTC, jujuck commented on server/src/cats/cat.resolvers.ts
> +      const checkEmail = await Cat.findOne({
A supprimer si contraintes d'unicité

2024-11-08 09:45 UTC, NicolasSokolowski commented on client/src/components/TimePicker/TimePicker.tsx
> +    let adjustedHours = hours;
Pour le composant Time Picker, je ne ré-affecte pas les minutes donc si je passe en "let", eslint n'est pas content...

2024-11-08 09:47 UTC, NicolasSokolowski commented on client/src/components/TimePicker/TimePicker.tsx
> +
Je passe ma string en number pour ré-affecter les heures pour ensuite repasser en string.
La méthode "padStart" ne fonctionne pas sur des nombres d'où l'utilisation de String sur les nombres récupérés auparavant.

2024-11-08 09:47 UTC, NicolasSokolowski commented on client/src/components/TimePicker/TimePicker.tsx
> +    const [hours, minutes] = hoursMinutes.split(":").map(Number);
Voir les commentaires précédents

2024-11-08 09:48 UTC, NicolasSokolowski commented on server/src/cats/cat.resolvers.ts
> +      where: { email: emailLowerCase },
Ok au final ça passe ainsi :)

2024-11-08 09:51 UTC, NicolasSokolowski commented on server/src/cats/cat.resolvers.ts
> +      const checkEmail = await Cat.findOne({
C'est supprimé car on a bien la contrainte d'unicité sur notre email dans l'entité Cat

2024-11-08 09:58 UTC, pjroggy approved these changes

2024-11-08 09:59 UTC, Pas-nou approved these changes

2024-11-08 10:20 UTC, jujuck approved these changes

2024-11-08 10:21 UTC, merged