Feature/create user list like
WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-1-Team-D pull request #9
Opened 2024-10-30 16:14 UTC by Pas-nou

Addition of the page where the user can view the chats he has liked.

2024-10-30 16:38 UTC, pjroggy approved these changes, later dismissed

2024-10-30 16:47 UTC, Ektoplasme commented on client/src/components/ProfileCard/ProfileLikeCard.css
> +    height: 232px;
Pourquoi ces valeurs exactement? On pourrait utiliser des valeurs rondes (160px et 230px)

2024-10-30 16:48 UTC, Ektoplasme commented on client/src/components/ProfileCard/ProfileLikeCard.css
> +  font-size: 18px;
Noter pour plus tard qu'on mettra cette valeur dans variables.css pour pouvoir la reutiliser sans s'emmeler les pinceaux (le fichier arrive dans la PR du layout)

2024-10-30 16:50 UTC, Ektoplasme commented on client/src/views/likes/Likes.tsx
> +  // console.log("je suis les data", data.likedCats)
👀

2024-10-30 16:50 UTC, Ektoplasme submitted a review, later dismissed
Hormis petits détails ça me paraît bien

2024-10-30 16:53 UTC, Pas-nou commented on client/src/components/ProfileCard/ProfileLikeCard.css
> +    height: 232px;
J'ai juste bêtement suivi les valeurs de la maquette, mais oui t'as raison 👍🏼

2024-10-30 16:55 UTC, Pas-nou commented on client/src/views/likes/Likes.tsx
> +  // console.log("je suis les data", data.likedCats)
🥲

2024-10-31 09:39 UTC, Ektoplasme submitted a review, later dismissed

2024-10-31 09:46 UTC, pjroggy submitted a review, later dismissed

2024-10-31 11:02 UTC, jujuck requested changes

2024-10-31 11:02 UTC, jujuck commented on client/src/components/ProfileCard/ProfileLikeCard.tsx
> +    <section className="profile-card-container">
Balise article

2024-10-31 11:02 UTC, jujuck commented on client/src/components/ProfileCard/ProfileLikeCard.tsx
> +      <section className="profile-card-text">
Désolé mais je pense que la div est approprié. Ceci n'est pas une section mais un effet de style pour ta carte

2024-10-31 11:02 UTC, jujuck commented on client/src/components/ProfileCard/ProfileLikeCard.css
> +
Ligne en trop

2024-10-31 11:02 UTC, jujuck commented on client/src/views/Likes/Likes.tsx
> +          <Select
Pas de fonctionnalité qui ne sert à rien

2024-10-31 11:02 UTC, jujuck commented on client/src/components/ProfileCard/ProfileLikeCard.tsx
> +        <h2 className="profile-texts">
Ton h2 est dans une section qui commence par un h3 (page parent)
Inverse les relations.
Il me semble que le titre de la page est plus important que le nom du chat liked

2024-10-31 11:02 UTC, jujuck commented on client/src/components/ProfileCard/ProfileLikeCard.tsx
> +        alt="photo de profil"
une balise alt doit être unique, concatène avec le nom du chat

2024-10-31 11:16 UTC, Ektoplasme approved these changes

2024-10-31 11:18 UTC, pjroggy approved these changes

2024-10-31 11:23 UTC, jujuck approved these changes

2024-10-31 11:23 UTC, merged